
import "./globals.css";
//import "./fanta.css";
//import Head from "./head";
//<Head />
import AuthProvider from "@/context/AuthContext";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Logo from "@/components/Logo";

export const metadata = {
    title: "MathMatters",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <AuthProvider>
                <body >
                    <div id="app">
                        <Header />
                        {children}
                        <Logo />
                        <Footer />
                    </div>
                </body>
            </AuthProvider>
        </html>
    );
}
